// Generated by scripts/make_ats_actors.py from one template for the per-ATS family — edit it there and rerun.
// Ashby Jobs API: input mapping onto the shared jobs core with the platform fixed. Pure, no I/O.
//  - search mode: every filter of ats-jobs-scraper, same field names; `ats` is always ['ashby']
//    (an `ats` value in a copied ats-jobs-scraper input is ignored)
//  - live mode (`companyUrls`): only Ashby board URLs / tokens are fetched; a bare token ("ramp")
//    means a Ashby board. Board URLs of other platforms are ignored with a warning and reported in
//    badRefs, so a run with nothing usable left ends SUCCEEDED with noBoardsMessage() (core actor_main)
import { normalizeInput } from './core/filters.js';
import { parseBoardRef } from './core/transform.js';

export const PLATFORM = 'ashby';
export const PLATFORM_NAME = 'Ashby';
const OTHER_NAMES = 'Greenhouse, Lever, Workable, Recruitee or Workday';
const BARE_TOKEN = /^[A-Za-z0-9][A-Za-z0-9_.%-]*$/;

const strList = (v) => (Array.isArray(v) ? v : typeof v === 'string' && v.trim() ? v.split(',') : [])
  .map((x) => String(x ?? '').trim())
  .filter(Boolean);

export function toScraperOptions(input = {}) {
  const { ats: _ignored, companyUrls, boards, ...rest } = input ?? {};
  const keep = [];
  const otherPlatformRefs = [];
  for (const ref of [...strList(companyUrls), ...strList(boards)]) {
    const b = parseBoardRef(ref);
    if (b && b.ats !== PLATFORM) otherPlatformRefs.push(ref);
    else keep.push(!b && BARE_TOKEN.test(ref) ? `${PLATFORM}:${ref}` : ref);
  }
  const opts = normalizeInput({ ...rest, ats: [PLATFORM], companyUrls: keep });
  opts.otherPlatformRefs = otherPlatformRefs;
  if (otherPlatformRefs.length) {
    opts.badRefs = [...opts.badRefs, ...otherPlatformRefs];
    opts.mode = 'live';
  }
  return opts;
}

export function otherPlatformWarning(refs) {
  return `Ignored ${refs.length} board URL(s) of other platforms (${refs.slice(0, 5).join(', ')}${refs.length > 5 ? ', ...' : ''}): `
    + `this Actor reads Ashby boards only. For ${OTHER_NAMES} boards use https://apify.com/factpipe/ats-jobs-scraper`;
}

/** Status message when live mode has no usable Ashby board (passed to runJobsActor). */
export function noBoardsMessage(badRefs) {
  return `No Ashby job-board URL in input (${badRefs.slice(0, 3).join(', ')}${badRefs.length > 3 ? ', ...' : ''}). `
    + 'This Actor reads Ashby boards only, e.g. https://jobs.ashbyhq.com/ramp or the board token "ramp". '
    + `For ${OTHER_NAMES} boards use https://apify.com/factpipe/ats-jobs-scraper; for a company's own careers page use `
    + 'https://apify.com/factpipe/company-jobs-scraper';
}
