// Generated by scripts/make_ats_actors.py from one template for the per-ATS family — edit it there and rerun.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { OUTPUT_FIELDS } from '../src/core/feed.js';
import { toScraperOptions, PLATFORM, PLATFORM_NAME } from '../src/scraper.js';

const SLUG = 'greenhouse-jobs-api';
const FAMILY = ['greenhouse-jobs-api', 'lever-jobs-api', 'ashby-jobs-api', 'workday-jobs-api'];
const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const readRepo = (p) => readFileSync(new URL(`../../../${p}`, import.meta.url), 'utf8');
const actor = JSON.parse(read('.actor/actor.json'));
const schema = JSON.parse(read('INPUT_SCHEMA.json'));
const PRICE = '$2 per 1,000 jobs';

test('actor.json: Store limits, platform name first, categories, price mention', () => {
  assert.equal(actor.name, SLUG);
  assert.ok(actor.title.length <= 60, `title ${actor.title.length} chars`);
  assert.ok(actor.title.startsWith(`${PLATFORM_NAME} `), actor.title);
  assert.ok(actor.description.length <= 220, `description ${actor.description.length} chars`);
  assert.ok(actor.description.includes(PRICE), actor.description);
  assert.deepEqual(actor.categories, ['JOBS', 'LEAD_GENERATION']);
});

test('dataset schema declares exactly the fields the Actor outputs (same as ats-jobs-scraper)', () => {
  assert.deepEqual(Object.keys(actor.storages.dataset.fields.properties), OUTPUT_FIELDS);
  for (const f of actor.storages.dataset.views.jobs.transformation.fields) assert.ok(OUTPUT_FIELDS.includes(f), f);
  for (const f of Object.keys(actor.storages.dataset.views.jobs.display.properties)) assert.ok(actor.storages.dataset.views.jobs.transformation.fields.includes(f), f);
  const model = JSON.parse(readRepo('actors/ats-jobs-scraper/.actor/actor.json'));
  assert.deepEqual(actor.storages.dataset.fields, model.storages.dataset.fields);
});

test('output schema has no resourceType; Dockerfile uses apify/actor-node:22', () => {
  assert.ok(!read('.actor/output_schema.json').includes('resourceType'));
  assert.match(read('.actor/Dockerfile'), /^FROM apify\/actor-node:22$/m);
});

test('src/lib is the synced shared copy; src/core is the synced ats-jobs-feed core (scripts/sync_jobs_core.py)', () => {
  for (const f of readdirSync(new URL('../../../shared/js/', import.meta.url)).filter((x) => x.endsWith('.js'))) {
    assert.equal(read(`src/lib/${f}`), readRepo(`shared/js/${f}`), `lib/${f} drifted: run python3 scripts/sync_shared.py`);
  }
  const src = new URL('../../ats-jobs-feed/src/core/', import.meta.url);
  const files = readdirSync(src).filter((f) => f.endsWith('.js')).sort();
  assert.deepEqual(readdirSync(new URL('../src/core/', import.meta.url)).filter((f) => f.endsWith('.js')).sort(), files);
  for (const f of files) assert.equal(read(`src/core/${f}`), readFileSync(new URL(f, src), 'utf8'), `core/${f} drifted: run python3 scripts/sync_jobs_core.py`);
});

test('input schema: no `ats`, same fields as ats-jobs-scraper otherwise, prefill accepted', () => {
  const model = JSON.parse(readRepo('actors/ats-jobs-scraper/INPUT_SCHEMA.json'));
  assert.ok(!('ats' in schema.properties));
  assert.deepEqual(Object.keys(schema.properties), Object.keys(model.properties).filter((k) => k !== 'ats'));
  for (const [k, p] of Object.entries(schema.properties)) {
    for (const attr of ['type', 'editor', 'enum', 'default', 'minimum', 'maximum', 'items']) assert.deepEqual(p[attr], model.properties[k][attr], `${k}.${attr}`);
  }
  const prefill = Object.fromEntries(Object.entries(schema.properties).filter(([, p]) => 'prefill' in p).map(([k, p]) => [k, p.prefill]));
  assert.deepEqual(prefill, { keywords: ['software engineer'], maxResults: 20, maxPerCompany: 3 });
  const o = toScraperOptions(prefill);
  assert.deepEqual([o.mode, o.ats, o.maxResults, o.maxPerCompany, o.includeDescription], ['search', [PLATFORM], 20, 3, true]);
});

test('PPE: one job-result per delivered job (the event the core charges), $2 per 1,000 in registry', () => {
  assert.match(read('src/core/feed.js'), /deps\.charge\(\{ eventName: 'job-result' \}\)/);
  const reg = JSON.parse(readRepo('registry.json')).actors[SLUG];
  assert.ok(reg, 'registry.json entry');
  assert.deepEqual(Object.keys(reg.ppe_events), ['job-result']);
  assert.equal(reg.ppe_events['job-result'].proposed_price_usd, 0.002);
  assert.deepEqual(reg.ppe_events['job-result'].store_discount_tiers_usd, { FREE: 0.002, BRONZE: 0.0018, SILVER: 0.0016, GOLD: 0.0014 });
  assert.equal(reg.listing.title, actor.title);
  assert.equal(reg.listing.description, actor.description);
  assert.ok(reg.listing.seoTitle.length <= 60 && reg.listing.seoDescription.length <= 160);
  assert.deepEqual(reg.listing.categories, actor.categories);
});

test('README: price, quick start cost, search keywords', () => {
  const md = read('README.md');
  assert.ok(md.startsWith(`# ${actor.title}\n`));
  assert.ok(md.includes(`**${PRICE}**`));
  assert.match(md, /## Quick start[\s\S]*\$0\.04 \(20 jobs × \$0\.002\)/);
  assert.match(md, /\| `job-result` \| \*\*\$2\.00 per 1,000\*\* \(\$0\.002 each\)/);
  for (const k of ['Greenhouse API', 'Greenhouse job board scraper', 'Greenhouse jobs API']) assert.ok(md.includes(k), k);
  assert.ok(!/\n\| `ats` \|/.test(md), 'README documents no `ats` input');
});

test('README: sections in order, related Actors before FAQ incl. the other per-ATS Actors, sample JSON parses', () => {
  const md = read('README.md');
  const at = (h) => md.indexOf(`\n## ${h}\n`);
  const order = ['Quick start', 'What you get', 'Use cases', 'Input', 'Pricing (pay per event)', 'factpipe Jobs Data', 'FAQ'].map(at);
  assert.ok(order.every((x, i) => x > 0 && (i === 0 || x > order[i - 1])), JSON.stringify(order));
  const suite = md.slice(at('factpipe Jobs Data'), at('FAQ'));
  for (const s of ['ats-jobs-feed', 'ats-jobs-scraper', 'remote-jobs-feed', 'companies-hiring', ...FAMILY]) assert.ok(suite.includes(`https://apify.com/factpipe/${s})`), s);
  assert.match(suite, new RegExp(`apify\\.com/factpipe/${SLUG}\\)[^\\n]*\\(this Actor\\)`));
  assert.match(md, /\*\*Switching from ats-jobs-scraper or other Greenhouse scrapers\?\*\*/);
  const sample = JSON.parse(md.match(/## What you get[\s\S]*?```json\n([\s\S]*?)\n```/)[1]);
  assert.deepEqual(Object.keys(sample), OUTPUT_FIELDS);
  assert.equal(sample.ats, PLATFORM);
});
