// Generated by scripts/make_ats_actors.py from one template for the per-ATS family — edit it there and rerun.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { runFeed, streamShardLines } from '../src/core/feed.js';
import { toScraperOptions, noBoardsMessage, otherPlatformWarning, PLATFORM } from '../src/scraper.js';
import { fakeNetwork, sink, NOW, buildIndex, assertMatchesSchema, FIXTURES, load } from './helpers.mjs';

const OWN = FIXTURES[PLATFORM];
const OTHER = 'lever';

async function run(input, { dir } = {}) {
  const out = sink();
  const net = fakeNetwork();
  const read = [];
  const summary = await runFeed(toScraperOptions(input), {
    ...out, indexBaseUrl: dir ? pathToFileURL(dir).href : undefined, now: () => NOW, hostGaps: {},
    fetchJson: net.fetchJson, fetchText: net.fetchText,
    streamShardLines: (base, rel) => { read.push(rel); return streamShardLines(base, rel); },
  });
  return { summary, rows: out.rows, charges: out.charges, calls: net.calls, read };
}

test('options: platform is forced, whatever `ats` says', () => {
  for (const ats of [undefined, [], ['lever'], ['greenhouse', 'lever', 'ashby', 'workable', 'recruitee', 'workday'], 'workable']) {
    const o = toScraperOptions({ ats, keywords: ['engineer'] });
    assert.deepEqual([o.mode, o.ats, o.keywords], ['search', [PLATFORM], ['engineer']], JSON.stringify(ats));
  }
  assert.deepEqual(toScraperOptions({}).ats, [PLATFORM]);
  assert.deepEqual(toScraperOptions(undefined).ats, [PLATFORM]);
});

test('options: same filters and defaults as ats-jobs-scraper', () => {
  const o = toScraperOptions({ keywords: 'a, b', locations: ['US'], remote: 'remote_only', postedWithinDays: 7, departments: ['eng'],
    employmentTypes: ['full_time'], companies: ['x'], excludeKeywords: ['senior'], maxPerCompany: 2, sinceLastRun: true,
    keywordMatch: 'all', keywordScope: 'title', includeDescription: false, maxResults: 5 });
  assert.deepEqual([o.keywords, o.locations, o.remote, o.postedWithinDays, o.departments, o.employmentTypes, o.companies, o.excludeKeywords],
    [['a', 'b'], ['US'], 'remote_only', 7, ['eng'], ['full_time'], ['x'], ['senior']]);
  assert.deepEqual([o.maxPerCompany, o.sinceLastRun, o.keywordMatch, o.keywordScope, o.includeDescription, o.maxResults], [2, true, 'all', 'title', false, 5]);
  const d = toScraperOptions({});
  assert.deepEqual([d.maxResults, d.includeDescription, d.remote, d.keywordScope, d.keywordMatch], [100, true, 'any', 'title_and_description', 'any']);
  assert.throws(() => toScraperOptions({ remote: 'mars' }), /remote/);
});

test('options: other-platform board URLs are dropped (with a warning), own URLs and bare tokens kept', () => {
  const own = 'https://job-boards.greenhouse.io/gitlab';
  const foreign = ['https://jobs.lever.co/shieldai', 'workable:acme', 'https://acme.recruitee.com'];
  const o = toScraperOptions({ companyUrls: [own, ...foreign, 'stripe', 'https://www.example.com/careers'] });
  assert.equal(o.mode, 'live');
  assert.ok(o.boards.every((b) => b.ats === PLATFORM), JSON.stringify(o.boards));
  assert.deepEqual(o.boards.map((b) => b.token.toLowerCase()), ['gitlab', 'stripe'.toLowerCase()].filter((t, i, a) => a.indexOf(t) === i));
  assert.deepEqual(o.otherPlatformRefs, foreign);
  assert.deepEqual(o.badRefs, ['https://www.example.com/careers', ...foreign]);
  assert.match(otherPlatformWarning(o.otherPlatformRefs), /^Ignored 3 board URL\(s\) of other platforms[\s\S]*Greenhouse boards only[\s\S]*ats-jobs-scraper/);
});

test('options: only other-platform URLs -> live mode with no boards (core exits SUCCEEDED with noBoardsMessage)', () => {
  const o = toScraperOptions({ companyUrls: ['https://jobs.lever.co/shieldai'] });
  assert.equal(o.mode, 'live');
  assert.deepEqual(o.boards, []);
  assert.deepEqual(o.badRefs, ['https://jobs.lever.co/shieldai']);
  const msg = noBoardsMessage(o.badRefs);
  assert.match(msg, /^No Greenhouse job-board URL in input \(/);
  assert.ok(msg.includes('https://apify.com/factpipe/ats-jobs-scraper'), msg);
  assert.ok(msg.length < 400, `status message ${msg.length} chars`);
});

test('search mode: only Greenhouse jobs, other-platform shards never downloaded, rows match the dataset schema', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'greenhouse-jobs-api-index-'));
  try {
    await buildIndex(dir);
    const r = await run({ ats: [OTHER], includeDescription: false }, { dir });
    assert.ok(r.rows.length > 0);
    assert.deepEqual(new Set(r.rows.map((x) => x.ats)), new Set([PLATFORM]));
    assert.ok(r.read.length > 0 && r.read.every((f) => f.includes(`/${PLATFORM}-`)), r.read.join(','));
    for (const x of r.rows) assertMatchesSchema(x);
    assert.equal(r.charges, r.rows.length, 'one job-result per delivered job');
    assert.equal(r.summary.mode, 'search');
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('search mode: maxResults caps delivery and charging', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'greenhouse-jobs-api-index-'));
  try {
    await buildIndex(dir);
    const r = await run({ maxResults: 1, includeDescription: false }, { dir });
    assert.equal(r.rows.length, 1);
    assert.equal(r.charges, 1);
    assert.equal(r.summary.stop_reason, 'max_results');
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('live mode: own board fetched, other-platform board ignored (never requested)', async () => {
  const r = await run({ companyUrls: [`${PLATFORM}:${OWN.token}`, `${OTHER}:${FIXTURES[OTHER].token}`] });
  assert.equal(r.summary.mode, 'live');
  assert.ok(r.rows.length > 0);
  assert.ok(r.rows.every((x) => x.ats === PLATFORM && x.company_board.toLowerCase() === OWN.token.toLowerCase()));
  assert.ok(r.rows.every((x) => x.description_status === 'included'));
  for (const x of r.rows) assertMatchesSchema(x);
  assert.equal(r.charges, r.rows.length);
  assert.ok(!r.calls.some((u) => u.includes(FIXTURES[OTHER].token)), r.calls.join(','));
});

test('golden fixture of this platform parses into schema-valid rows', async () => {
  assert.ok(load(OWN.file));
  const r = await run({ companyUrls: [OWN.token], includeDescription: false });
  assert.ok(r.rows.length > 0);
  for (const x of r.rows) assertMatchesSchema(x);
  assert.ok(r.rows.every((x) => x.description_status === 'not_requested'));
});
