// Generated by scripts/make_ats_actors.py from one template for the per-ATS family — edit it there and rerun.
import { log } from 'apify';
import { runJobsActor } from './core/actor_main.js';
import { toScraperOptions, noBoardsMessage, otherPlatformWarning } from './scraper.js';

await runJobsActor({
  slug: 'lever-jobs-api',
  toOptions: (input) => {
    const opts = toScraperOptions(input);
    if (opts.otherPlatformRefs.length) log.warning(otherPlatformWarning(opts.otherPlatformRefs));
    return opts;
  },
  noBoardsMessage,
});
